'\" t
.\"     Title: heat jeos
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 03/31/2012
.\"    Manual: System administration commands
.\"    Source: Heat 0.0.1
.\"  Language: English
.\"
.TH "HEAT JEOS" "1" "03/31/2012" "HEAT JEOS 0\&.0\&.1" "System administration commands"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
heat-jeos \- build JEOS images for use in Heat
.SH "SYNOPSIS"
.sp
heat-jeos list
.sp
heat-jeos create (<name> | --template-file=FILE) <options>
.sp
heat-jeos help <command>
.SH "DESCRIPTION"
.sp
\fBheat\-jeos\fR is a tool to build Just Enough Operating System (JEOS) images
for use by Heat and other OpenStack projects\&.
.sp
The created images will be set up with \fBcloud\-init\fR and \fBcfntools\fR\&.
This will provide an easier way to set up and provision the instances after
they're launched. This can be disabled with the \fB\-\-gold\fR switch\&.
.sp
Optionally, \fBheat\-jeos\fR will register the generated image with \fBOpenStack
Glance\fR\&.
.SH "ARGUMENTS"
.PP
\fBname\fR
.RS 4
Name of the input template\&. Must be one of the names from
\fBheat-jeos list\fR\&.
.RE
.PP
\fBcommand\fR
.RS 4
heat-jeos command\&. This can be either \fBlist\fR or \fBcreate\fR\&.
.RE
.SH "OPTIONS"
.PP
\fB\-t\fR, \fB\-\-template\-file=FILE\fR
.RS 4
path to a custom Oz template FILE
.RE
.PP
\fB\-a\fR, \fB\-\-auto\-file=FILE\fR
.RS 4
path to a custom auto file to use (e.g. kickstart or preseed) can be http / https
.RE
.PP
\fB\-s\fR, \fB\-\-iso=FILE\fR
.RS 4
override the OS installation media specified in the template with the custom iso
FILE
.RE
.PP
\fB\-g\fR, \fB\-\-gold\fR
.RS 4
build a gold image; \fBcfntools\fR will not be included
.RE
.PP
\fB\-G\fR, \fB\-\-register\-with\-glance\fR
.RS 4
register the image with \fBOpenStack Glance\fR after it's been built
.RE
.PP
\fB\-H\fR, \fB\-\-glance\-host=HOSTNAME\fR
.RS 4
connect to \fBGlance\fR at HOSTNAME
.RE
.PP
\fB\-P\fR, \fB\-\-glance\-port=PORT\fR
.RS 4
connect to \fBGlance\fR using PORT number
.RE
.PP
\fB\-y\fR, \fB\-\-yes\fR
.RS 4
don't prompt for user input; assume the answer to every question is \fByes\fR
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
print verbose output
.RE
.PP
\fB\-d\fR, \fB\-\-debug\fR
.RS 4
print debug messages
.RE
.PP
\fB\-c\fR, \fB\-\-cfn-dir=DIR\fR
.RS 4
use the \fBcfntools\fR located at DIR
.RE
.PP
\fB\-j\fR, \fB\-\-jeos-dir=DIR\fR
.RS 4
use the Oz templates from DIR directory
.RE
.PP
.SH "AUTHOR"
.sp
See the AUTHORS file for a complete list of contributors\&.
.SH "COPYRIGHT"
.sp
Copyright \(co 2012, Red Hat Inc
.sp
heat-jeos is released under the terms of the ASL 2 License\&.
.sp
Extensive documentation as well as IRC and mailing list info is available on the heat home page: https://heat\&-api\&.org/
